### ISSUE TITLE
Upgrading ttn-lw-stack to 3.12.0 fails

### ISSUE THREAD

**Issue by jchonig** [TheThingsNetwork/homebrew-lorawan-stack#1]
`==> Upgrading thethingsnetwork/lorawan-stack/ttn-lw-stack 3.11.3 -> 3.12.0
==> Downloading https://github.com/TheThingsNetwork/lorawan-stack/releases/download/v3.12.0/lorawan-stack_3.12.0_darwin_amd64.tar.gz
Already downloaded: /Users/jch/Library/Caches/Homebrew/downloads/edd73f4624ec41899fa023fa25a8529eb2a37d73b9e9f026619ad5731e461edc--lorawan-stack_3.12.0_darwin_amd64.tar.gz
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory - public`

**Comment by jchonig** [comment]
Here's a --debug install
`jch@jch-mbp[601]:~$ brew upgrade --debug ttn-lw-stack
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/thethingsnetwork/homebrew-lorawan-stack/ttn-lw-stack.rb
==> Upgrading 1 outdated package:
thethingsnetwork/lorawan-stack/ttn-lw-stack 3.11.3 -> 3.12.0
==> Upgrading thethingsnetwork/lorawan-stack/ttn-lw-stack 3.11.3 -> 3.12.0
==> Downloading https://github.com/TheThingsNetwork/lorawan-stack/releases/download/v3.12.0/lorawan-stack_3.12.0_darwin_amd64.tar.gz
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/3.0.11-104-g77a360b\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 11.2.3\)\ curl/7.64.1 --header Accept-Language:\ en --retry 3 --location --silent --head --request GET https://github.com/TheThingsNetwork/lorawan-stack/releases/download/v3.12.0/lorawan-stack_3.12.0_darwin_amd64.tar.gz
Already downloaded: /Users/jch/Library/Caches/Homebrew/downloads/edd73f4624ec41899fa023fa25a8529eb2a37d73b9e9f026619ad5731e461edc--lorawan-stack_3.12.0_darwin_amd64.tar.gz
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Homebrew/Library/Taps/thethingsnetwork/homebrew-lorawan-stack/ttn-lw-cli.rb
/usr/local/Homebrew/Library/Homebrew/shims/scm/git --version
tar xof /Users/jch/Library/Caches/Homebrew/downloads/edd73f4624ec41899fa023fa25a8529eb2a37d73b9e9f026619ad5731e461edc--lorawan-stack_3.12.0_darwin_amd64.tar.gz -C /private/tmp/d20210408-83959-1c1v5pk
cp -pR /private/tmp/d20210408-83959-1c1v5pk/lorawan-stack_3.12.0_darwin_amd64/. /private/tmp/ttn-lw-stack-20210408-83959-14xq53f/lorawan-stack_3.12.0_darwin_amd64
/usr/local/Homebrew/Library/Homebrew/debrew.rb:31:in `block in raise'
Errno::ENOENT: No such file or directory - public
1. raise
2. ignore
3. backtrace
4. irb
5. shell
Choose an action: 3
/usr/local/Homebrew/Library/Homebrew/debrew.rb:31:in `block in raise'
/usr/local/Homebrew/Library/Homebrew/debrew.rb:30:in `callcc'
/usr/local/Homebrew/Library/Homebrew/debrew.rb:30:in `raise'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:120:in `install_p'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:104:in `block (2 levels) in install'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:104:in `each'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:104:in `block in install'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:93:in `each'
/usr/local/Homebrew/Library/Homebrew/extend/pathname.rb:93:in `install'
/usr/local/Homebrew/Library/Taps/thethingsnetwork/homebrew-lorawan-stack/ttn-lw-stack.rb:36:in `install'
/usr/local/Homebrew/Library/Homebrew/debrew.rb:45:in `block in install'
/usr/local/Homebrew/Library/Homebrew/debrew.rb:119:in `debrew'
/usr/local/Homebrew/Library/Homebrew/debrew.rb:45:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:174:in `block (2 levels) in install'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1241:in `block in brew'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2301:in `block (2 levels) in stage'
/usr/local/Homebrew/Library/Homebrew/utils.rb:558:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2300:in `block in stage'
/usr/local/Homebrew/Library/Homebrew/resource.rb:121:in `block (2 levels) in unpack'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:115:in `chdir'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:115:in `chdir'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:102:in `stage'
/usr/local/Homebrew/Library/Homebrew/resource.rb:117:in `block in unpack'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:63:in `block in run'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:63:in `chdir'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:63:in `run'
/usr/local/Homebrew/Library/Homebrew/resource.rb:198:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/resource.rb:116:in `unpack'
/usr/local/Homebrew/Library/Homebrew/resource.rb:91:in `stage'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2280:in `stage'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1234:in `brew'
/usr/local/Homebrew/Library/Homebrew/build.rb:138:in `block in install'
/usr/local/Homebrew/Library/Homebrew/utils.rb:558:in `with_env'
/usr/local/Homebrew/Library/Homebrew/build.rb:133:in `install'
/usr/local/Homebrew/Library/Homebrew/build.rb:225:in `<main>'
1. raise
2. ignore
3. backtrace
4. irb
5. shell`

**Comment by htdvisser** [comment]
This issue was fixed in later versions.
